### ISSUE TITLE
Not Compatible with Safari/Apple Books

### ISSUE THREAD

**Issue by NoaHimesaka1873** [devplayer0/cvos#2]
Safari doesn't recognise pre-comfiled pdf as pdf file, and trying to read from Apple Books app crashes it.
Proof: https://youtu.be/mxBi_vIhomw

**Comment by devplayer0** [comment]
Hmmm. I assume by Safari you mean Safari on iOS? Unfortunately there's probably not a whole lot that can be done about this. I have no idea what exactly is causing the crash, probably the fact that the data extends far beyond the end of the PDF.

On a side note: _why the OwO'ified strings?_ :sweat_smile:

**Comment by NoaHimesaka1873** [comment]
It's jailbroken iPhone with tweak named OwO. Yes, I mean Safari for iOS.

**Comment by hanickadot** [comment]
I don’t have such problem on my iPhone. I can read the pdf example without crash on Xs.

**Comment by NoaHimesaka1873** [comment]
@hanickadot What version of iOS are you currently using? I'm on iPhone with iOS 12.1.1b3 jailbroken with Chimera.

**Comment by hanickadot** [comment]
12.3.1
